FROM bitnami/minideb:%%TAG%%

RUN \
  apt-get -qq update && \
  apt-get -qq install \
    incron


####

COPY entrypoint.sh /

#https://github.com/docker-library/postgres/issues/296#issuecomment-308735942
RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/usr/sbin/incrond", "-n" ]
