FROM bitnami/minideb:%%TAG%%

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN install_packages \
      incron \
    ;

COPY entrypoint.sh /

#https://github.com/docker-library/postgres/issues/296#issuecomment-308735942
RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/usr/sbin/incrond", "-n" ]
